import logging
import whatsapp.whatsapp_service as whatsapp_service
import bot.session as session
from bot.ai_service import get_ai_response

logger = logging.getLogger(__name__)

# Maximum number of conversation turns kept in memory per session.
# Each "turn" = 1 user message + 1 assistant reply = 2 list items.
# Keeping the window short reduces token usage and avoids stale context
max_history_turns: int = 10
ORDER_MARKER: str = "ORDER_CONFIRMED:"

def handle_text_message(sender: str, body: str) -> dict:
    """
    Main entry point for incoming messages.
    Fetches the session, checks for global comands, and delegates to the apropriate handler.
    Args:
        sender (str): number of the user that sent the message.
        body (str): text that the client sent.
    Returns:
        dict: the dict of the section uptaded with the new state
    """
    text = body
    logger.info("Handling text message from %s: %.80s", sender, text)
    
    # load the existing session
    _session: dict = session.get_session(sender) # get the session of the client
    history: list[dict[str, str]] = _session.get("history", [])
    
    # Append the new user turn to the history
    _add_to_history(history, "user", text)

    # call the AI to give a response
    try:
        raw_response: str = get_ai_response(_trim_history(history))
    except RuntimeError as exc:
        logger.error("AI service error for sender %s: %s", sender, exc)
        raw_response = (
            "Perdão, aconteceu uma instabilidade agora."
            "Poderia reenviar a mensagem ou chamar outro atendente?"
        )

    order: dict | None = _extract_order(raw_response)
    if order is not None:
        session.save_order(sender, order)
    
    response = _strip_order_block(raw_response)
    
    # Append the assistant reply to history
    _add_to_history(history, "assistant", response)
    _session["history"] = _trim_history(history)
    
    whatsapp_service.send_message(sender, response)


#
# PRIVATE METHODS
#

def _trim_history(history: list[dict[str, str]]) -> list[dict[str, str]]:
    """
    Keeps only the most recent max_history_turns turns, for short token usage porpouses.
    
    Each turns is a user+assistant pair (2 items). We calculate the max number of list items and slice from the end to preserve recency
    
    Args:
        history (list[dict[str, str]]): conversation history list

    Returns:
        list[dict[str, str]]: trimmed list with the most recent items. Minimum of 2 items returning.
    """
    
    max_items: int = max_history_turns * 2
    if len(history) > max_items:
        return history[-max_items:] #here we use - to trim from the end of the list and keep only the recent items
    
    return history
    

    
def _add_to_history(history: list, role: str, content: str) -> None:
    """
    Add to the history in the correct format.
    Minimizes rewriting the same thing.
    
    Args:
        history (list): the conversation history list to append to.
        role (str): is either user ou attendant
        content (str): response from user, attendant or system.
    """
    allowed_roles: set = {"user", "assistant"}

    if role not in allowed_roles:
        raise ValueError(f"Role inválida: {role!r}")

    history.append({"role": role, "content": content})  

def _extract_order(response: str) -> dict | None:
    """
    The AI is instructed to append an ORDER_CONFIRMED: JSON block when a
    customer confirms an order. 
    This function is responsible of extracting the json block out of the
    response of the LLM before sending it to the user.

    Args:
        response (str): Text generated by the LLM

    Returns:
        dict | None: Returns a dict with 'items' and 'total' or None if the no order block was sent.
    """
    
    if ORDER_MARKER not in response:
        return None
    
    _, json_part = response.split(ORDER_MARKER, maxsplit=1)
    
    try:
        return json.loads(json_part.strip()) 
    except json.JSONDecodeError:
        #working with small LLMs on test may cause malformed json or the LLM of the production can hallucinate. Log and ignore
        logger.warning("ORDER_CONFIRMED marker found but JSON was malformed: %s", json_part[:200])
        return None
    
def _strip_order_block(response: str) -> str:
    """
    Remove the order bloc from the message that the LLM sent

    Args:
        response (str): untreated text from the LLM.

    Returns:
        str: Text with the order block removed.
    """
    
    if ORDER_MARKER not in response:
        return response
    
    clean_response, _ = response.split(ORDER_MARKER, maxsplit=1)
    return clean_response.strip()
